// Code generated by "shoot rest -type=Client"; DO NOT EDIT. (v0.9.0-beta.1)

package github

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/loopopen/shoot"
)

type client struct {
	client         *http.Client
	conf           *shoot.RestConf
	defaultTimeout time.Duration
}

func (_c *client) ListOrgsForUser(ctx context.Context, per_page *int, page *int) ([]*Org, *http.Response, error) {
	path_ := "/user/orgs"

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "GET", url_, nil)
	if err != nil {
		return nil, nil, err
	}

	query_ := req_.URL.Query()
	if per_page != nil {
		query_.Set("per_page", fmt.Sprintf("%v", *per_page))
	}
	if page != nil {
		query_.Set("page", fmt.Sprintf("%v", *page))
	}
	req_.URL.RawQuery = query_.Encode()

	req_.Header.Set("Accept", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	req_.Header.Set("Accept", "application/vnd.github+json")

	req_.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	cleanupRequest_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)

	if err != nil {
		return nil, nil, err
	}
	defer func() {
		if cleanupRequest_ != nil {
			cleanupRequest_()
		}
	}()

	resp_, err := _c.client.Do(req_)
	if err != nil {
		return nil, nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	resp_.Body = io.NopCloser(bytes.NewReader(responseBody_))
	response_ := resp_
	if err != nil {
		return nil, response_, err
	}
	if closeErr_ != nil {
		return nil, response_, closeErr_
	}

	var r_ []*Org
	err = json.NewDecoder(bytes.NewReader(responseBody_)).Decode(&r_)
	if err == io.EOF {
		err = nil //ignore EOF errors caused by empty response body
	}
	if err != nil {
		return nil, response_, err
	}
	return r_, response_, nil
}

func (_c *client) ListProjectsForUser(ctx context.Context, username string, beforce *string, after *string, per_page *int) ([]*ProjectV2, *http.Response, error) {
	path_ := "/users/{username}/projectsV2"
	path_ = strings.Replace(path_, "{username}", url.PathEscape(fmt.Sprint(username)), 1)

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "GET", url_, nil)
	if err != nil {
		return nil, nil, err
	}

	query_ := req_.URL.Query()
	if beforce != nil {
		query_.Set("beforce", fmt.Sprintf("%v", *beforce))
	}
	if after != nil {
		query_.Set("after", fmt.Sprintf("%v", *after))
	}
	if per_page != nil {
		query_.Set("per_page", fmt.Sprintf("%v", *per_page))
	}
	req_.URL.RawQuery = query_.Encode()

	req_.Header.Set("Accept", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	req_.Header.Set("Accept", "application/vnd.github+json")

	req_.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	cleanupRequest_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)

	if err != nil {
		return nil, nil, err
	}
	defer func() {
		if cleanupRequest_ != nil {
			cleanupRequest_()
		}
	}()

	resp_, err := _c.client.Do(req_)
	if err != nil {
		return nil, nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	resp_.Body = io.NopCloser(bytes.NewReader(responseBody_))
	response_ := resp_
	if err != nil {
		return nil, response_, err
	}
	if closeErr_ != nil {
		return nil, response_, closeErr_
	}

	var r_ []*ProjectV2
	err = json.NewDecoder(bytes.NewReader(responseBody_)).Decode(&r_)
	if err == io.EOF {
		err = nil //ignore EOF errors caused by empty response body
	}
	if err != nil {
		return nil, response_, err
	}
	return r_, response_, nil
}

func (_c *client) ListReposForOrg(ctx context.Context, org string, typ *string, per_page *int, page *int) ([]*Repo, *http.Response, error) {
	path_ := "/orgs/{org}/repos"
	path_ = strings.Replace(path_, "{org}", url.PathEscape(fmt.Sprint(org)), 1)

	url_, err := url.JoinPath(_c.conf.BaseURL(), path_)
	if err != nil {
		return nil, nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "GET", url_, nil)
	if err != nil {
		return nil, nil, err
	}

	query_ := req_.URL.Query()
	if typ != nil {
		query_.Set("type", fmt.Sprintf("%v", *typ))
	}
	if per_page != nil {
		query_.Set("per_page", fmt.Sprintf("%v", *per_page))
	}
	if page != nil {
		query_.Set("page", fmt.Sprintf("%v", *page))
	}
	req_.URL.RawQuery = query_.Encode()

	req_.Header.Set("Accept", "application/json")

	for headerName_, headerValue_ := range _c.conf.DefaultHeaders() {
		req_.Header.Set(headerName_, headerValue_)
	}

	req_.Header.Set("Accept", "application/vnd.github+json")

	req_.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	cleanupRequest_, err := shoot.ApplyRequestOptions(req_, _c.defaultTimeout)

	if err != nil {
		return nil, nil, err
	}
	defer func() {
		if cleanupRequest_ != nil {
			cleanupRequest_()
		}
	}()

	resp_, err := _c.client.Do(req_)
	if err != nil {
		return nil, nil, err
	}
	responseBody_, err := io.ReadAll(resp_.Body)
	closeErr_ := resp_.Body.Close()
	resp_.Body = io.NopCloser(bytes.NewReader(responseBody_))
	response_ := resp_
	if err != nil {
		return nil, response_, err
	}
	if closeErr_ != nil {
		return nil, response_, closeErr_
	}

	var r_ []*Repo
	err = json.NewDecoder(bytes.NewReader(responseBody_)).Decode(&r_)
	if err == io.EOF {
		err = nil //ignore EOF errors caused by empty response body
	}
	if err != nil {
		return nil, response_, err
	}
	return r_, response_, nil
}

// ConfigHTTPClient allows customization of the underlying http.Client.
func (_c *client) ConfigHTTPClient(config func(*http.Client)) Client {
	config(_c.client)
	return _c
}

// ShootRest exists solely to fulfill the RestShooter interface contract.
func (_c *client) ShootRest() { /*noop*/ }

func init() {
	shoot.Register(func(conf shoot.RestConf) Client {
		timeout, err := time.ParseDuration(conf.Timeout())
		if err != nil {
			panic(err)
		}
		return &client{
			conf:           &conf,
			defaultTimeout: timeout,
			client: &http.Client{
				Transport: conf.BuildMiddleware(),
			},
		}
	})
}
